[package]
name = "linkz"
version = "0.2.0"
edition = "2021"

[dependencies]
tokio = { version = "1.26.0", features = ["full"] }
hyper ={ version = "0.14.25", features = ["server", "http1", "backports", "runtime"] }
